repos:
-   repo: https://github.com/python/black
    rev: 22.1.0
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]